version: '3.8'

services:
  client:
    container_name: client-c
    image: client-i
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    container_name: server-c
    image: server-i
    build:
      context: "./server"
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app