version: "3"

services:
  # server-prod:
  #   container_name: orcinus-server-prod
  #   image: mitczubi/orcinus-server-prod
  #   build:
  #     context: ./server
  #     dockerfile: docker-setup/nodejs/production/Dockerfile
  #   networks:
  #     - frontend
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - ./server/.env.production
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - "4000:4000"

  client-prod:
    container_name: orcinus-client-prod
    image: mitczubi/orcinus-client-prod
    build:
      context: ./client
      dockerfile: docker-setup/react/production/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - server-prod
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

networks:
  frontend:
    name: orcinus-frontend-network
